### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by anquandebaihuli** [CokeSR/Hk4e-SDKSever-Py#10]
登陆提示 错误的登陆格式，是什么原因，账号已注册

**Comment by anquandebaihuli** [comment]
处理请求事件发生以外错误err=InvalidURL('Failed to parse: http://192.168.3.8:221605/query_cur_region?'), type(err)=<class 'requests.exceptions.InvalidURL'>
处理请求事件发生以外错误err=InvalidURL('Failed to parse: http://192.168.3.8:222805/query_cur_region?'), type(err)=<class 'requests.exceptions.InvalidURL'>
处理登录事件时出现意外错误 err=ValueError('No PEM start marker "b\'-----BEGIN RSA PRIVATE KEY-----\'" found')，type(err)=<class 'ValueError'>
处理登录事件时出现意外错误 err=ValueError('No PEM start marker "b\'-----BEGIN RSA PRIVATE KEY-----\'" found')，type(err)=<class 'ValueError'>
处理登录事件时出现意外错误 err=ValueError('No PEM start marker "b\'-----BEGIN RSA PRIVATE KEY-----\'" found')，type(err)=<class 'ValueError'>

**Comment by CokeSR** [comment]
不支持用用户名登录 请用手机号或邮箱 或者你自己改代码
因为没写密码验证所以报错 请你关掉密码验证
